version: '3.8'

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:13-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./dockerConfig/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: product_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    networks:
      - product_api_network
  app:
    container_name: product_api_app
    restart: always
    depends_on:
      - postgres_db
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    networks:
      - product_api_network
    env_file:
      - .env
    environment:
      - PG_HOST=${PG_HOST}
      #- POSTGRES_DB=product_api
      #- POSTGRES_USER=postgres
      #- POSTGRES_PASS=postgres
    volumes:
      - ./:/home/node/product_api
    command: dumb-init node ace serve --watch


networks:
  product_api_network:
    driver: bridge

volumes:
  postgres_volume:
